### ISSUE TITLE
Cannot interrogate XHR

### ISSUE THREAD

**Issue by PsychicSmurf** [jeffhatz/AJAX-Debugger#1]
I have this extension on 2 machines.

The first, my Windows 7 box, and everything is working fine.
However, on my XP SP3 box, the extension does not perform as intended.

I get the same list of events, as per my Win7 box, but if I click on the XHR Loaded event to 'open' it and show more details (eg URL/parameters etc), the left hand arrow changes to point down (correctly), but the content doesn't expand to show the contents. So the line of text stays unchanged, and I can't inspect the contents.

Clicking on it again makes the arrow change back.

Chrome: Version 31.0.1650.57 m
Windows XP SP3, all latest patches.

**Comment by jeffhatz** [comment]
I am unable to reproduce the issue on Win XP SP3 with the same version of Chrome — the details open as expected. I tried various combinations of the extension's options, and it continued to work as expected.

Is it happening on one page/site, or every Ajax call? Is there a public URL that exhibits the behavior that I would be able to look at? Does removing and re-installing the extension solve the problem?

**Comment by jeffhatz** [comment]
I just ran across this issue, and in my case it was caused because I had Console filtered to show just errors. The items within the group are log items, so Chrome was filtering them out.
